/* Automatically generated by 'build-entry.js' */

import MiForm from './MiForm/index.js';
import MiTable from './MiTable/index.js';
import MiCity from './MiCity/index.js';
import MiNotify from './MiNotify/index.js';
import MiTab from './MiTab/index.js';
import MiMenu from './MiMenu/index.js';
import MiModalForm from './MiModalForm/index.js';
import MiProgress from './MiProgress/index.js';
/* 导入组件库所有组件 */
const components = [
  MiForm,
  MiTable,
  MiCity,
  MiNotify,
  MiTab,
  MiMenu,
  MiModalForm,
  MiProgress
];

/* 定义组件库组件注册安装的install方法, 当使用 use 注册插件，则所有的组件都将被注册 */
const install = function (app) {
  components.map((item) => {
    app.use(item);
  });
}

export default {
  /* 导出的对象必须具有 install，才能被 app.use() 方法安装 */
  install,
  MiForm,
  MiTable,
  MiCity,
  MiNotify,
  MiTab,
  MiMenu,
  MiModalForm,
  MiProgress
};
